title: Kayode Omotayo | Data Analyst
description: Data analyst with 6+ years of experience in SQL, Python, Power BI, and cloud analytics. Specializing in automation, reporting, and actionable business insights.
theme: jekyll-theme-minimal

author:
  name: Kayode Omotayo
  email: omotayo.kayode@gmail.com

url: https://kayode-the-analyst.github.io
baseurl: "/analytics-portfolio"

linkedin_username: kayodetheanalyst

plugins:
  - jekyll-seo-tag

logo: 314A0842.jpg

