title: Kayode Omotayo | Data Analyst
logo: 314A0842.jpg
description: Data analyst with 6+ years of experience in SQL, Python, Power BI, and cloud analytics, delivering automated reporting and actionable business insights.
theme: jekyll-theme-minimal







